/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HW_H_RPCGEN
#define _HW_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct params {
	char *conteudo;
	char *usuario;
	int contador;
};
typedef struct params params;

#define PROG 0x31279999
#define VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define func1 1
extern  int * func1_1(params *, CLIENT *);
extern  int * func1_1_svc(params *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define func1 1
extern  int * func1_1();
extern  int * func1_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_params (XDR *, params*);

#else /* K&R C */
extern bool_t xdr_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HW_H_RPCGEN */
